/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.View {
    export class LoadingUI extends Scene {
        public static  uiView:any ={"type":"Scene","props":{"width":750,"top":0,"right":0,"left":0,"height":1334,"bottom":0},"compId":2,"child":[{"type":"Image","props":{"x":0,"width":750,"top":0,"skin":"GameCommon/bgbg.png","height":2000},"compId":12},{"type":"Image","props":{"top":0,"right":0,"name":"Bg","left":0,"hitTestPrior":true,"bottom":0},"compId":6,"child":[{"type":"Sprite","props":{"y":1083,"x":64,"width":620,"texture":"GameCommon/bg12.png","name":"processBarBg","height":65},"compId":9,"child":[{"type":"Clip","props":{"y":11,"x":12,"width":597,"skin":"GameCommon/bg11.png","name":"processBar","height":40,"sizeGrid":"0,10,0,10"},"compId":11}]},{"type":"Sprite","props":{"y":1005,"x":241,"texture":"GameCommon/jiazaizhong.png","scaleY":1.5,"scaleX":1.5},"compId":13},{"type":"Sprite","props":{"y":467,"x":175,"texture":"GameCommon/41_0016_logo.png"},"compId":14}]},{"type":"Script","props":{"y":0,"x":0,"runtime":"View/LoadingView/LoadingView.ts"},"compId":7}],"loadList":["GameCommon/bgbg.png","GameCommon/bg12.png","GameCommon/bg11.png","GameCommon/jiazaizhong.png","GameCommon/41_0016_logo.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(LoadingUI.uiView);
        }
    }
    REG("ui.View.LoadingUI",LoadingUI);
}