/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameMgr from "./Mgr/GameMgr"
import ButtonAnim from "./View/ButtonAnim"
import LoopAdBox from "./ShareAd/View/LoopAdBox"
import LoopAdView from "./ShareAd/View/LoopAdView"
import ExportView from "./View/Game/ExportView"
import GameFailureView from "./View/Game/GameFailureView"
import TextureProcessBar from "./View/TextureProcessBar"
import GameLoadingView from "./View/Game/GameLoadingView"
import SongDisCell from "./View/Game/CellView/SongDisCell"
import CenterList from "./View/Game/CenterList"
import GameMainView from "./View/Game/GameMainView"
import GameSettleView from "./View/Game/GameSettleView"
import GameWorkView from "./View/Game/GameWorkView"
import LoadingView from "./View/LoadingView/LoadingView"
import SongStoreCell from "./View/Game/CellView/SongStoreCell"
import SongStoreView from "./View/Game/SongStoreView"
import TipsView from "./View/TipsView/TipsView"
import HorizontalLoopAdView from "./ShareAd/View/HorizontalLoopAdView"
import BannerAdView from "./ShareAd/View/BannerAdView"
import UniversalBottomZone from "./View/Common/UniversalBottomZone"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=1080;
    static height:number=1920;
    static scaleMode:string="fixedwidth";
    static screenMode:string="vertical";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="GameMain.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=false;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("Mgr/GameMgr.ts",GameMgr);
        reg("View/ButtonAnim.ts",ButtonAnim);
        reg("ShareAd/View/LoopAdBox.ts",LoopAdBox);
        reg("ShareAd/View/LoopAdView.ts",LoopAdView);
        reg("View/Game/ExportView.ts",ExportView);
        reg("View/Game/GameFailureView.ts",GameFailureView);
        reg("View/TextureProcessBar.ts",TextureProcessBar);
        reg("View/Game/GameLoadingView.ts",GameLoadingView);
        reg("View/Game/CellView/SongDisCell.ts",SongDisCell);
        reg("View/Game/CenterList.ts",CenterList);
        reg("View/Game/GameMainView.ts",GameMainView);
        reg("View/Game/GameSettleView.ts",GameSettleView);
        reg("View/Game/GameWorkView.ts",GameWorkView);
        reg("View/LoadingView/LoadingView.ts",LoadingView);
        reg("View/Game/CellView/SongStoreCell.ts",SongStoreCell);
        reg("View/Game/SongStoreView.ts",SongStoreView);
        reg("View/TipsView/TipsView.ts",TipsView);
        reg("ShareAd/View/HorizontalLoopAdView.ts",HorizontalLoopAdView);
        reg("ShareAd/View/BannerAdView.ts",BannerAdView);
        reg("View/Common/UniversalBottomZone.ts",UniversalBottomZone);
    }
}
GameConfig.init();