/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package game.ui.View {
	import laya.ui.*;import laya.display.*; 
	import laya.display.Text;
	import Tips_wcjtn_View;

	public class TipsViewUI extends View {

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{"width":1920,"top":0,"right":0,"name":"TipsView","mouseThrough":true,"left":0,"height":1080,"bottom":0},"compId":2,"child":[{"type":"Clip","props":{"y":264,"x":539,"width":841,"skin":"Common/提示框拉伸.png","name":"Bg","mouseThrough":true,"height":159},"compId":3,"child":[{"type":"Text","props":{"y":12,"x":23,"width":795,"valign":"middle","name":"Text","mouseThrough":true,"height":134,"fontSize":40,"color":"#ffffff","align":"center","runtime":"laya.display.Text"},"compId":5}]},{"type":"Script","props":{"runtime":"Tips_wcjtn_View"},"compId":6}],"loadList":["Common/提示框拉伸.png"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}