/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package game.ui.View {
	import laya.ui.*;import laya.display.*; 
	import LoopAd_wcjtn_Box;
	import laya.display.Text;
	import Horizontal_wcjtn_LoopAd_wcjtn_View;
	import Banner_wcjtn_Ad_wcjtn_View;
	import Universal_wcjtn_BottomZone;

	public class UniversalBottomZoneUI extends View {

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{"width":750,"height":1334},"compId":2,"child":[{"type":"Clip","props":{"right":0,"name":"BottomZone","left":0,"height":750,"bottom":0},"compId":3,"child":[{"type":"Clip","props":{"skin":"comp/clip_num.png","right":0,"name":"AutoZone","left":0,"height":250,"bottom":250},"compId":8},{"type":"Clip","props":{"skin":"comp/clip_num.png","right":0,"name":"LoopAD","left":0,"height":200,"bottom":0},"compId":6,"child":[{"type":"List","props":{"top":0,"spaceX":9,"right":0,"repeatY":1,"name":"List","left":0,"bottom":0},"compId":10,"child":[{"type":"Box","props":{"y":10,"x":0,"width":180,"renderType":"render","height":180},"compId":11,"child":[{"type":"Script","props":{"runtime":"LoopAd_wcjtn_Box"},"compId":13},{"type":"Sprite","props":{"y":5,"x":5,"width":170,"name":"Display","height":170},"compId":14},{"type":"Text","props":{"y":128,"x":5,"width":170,"valign":"middle","text":"ZongSoftWare","name":"TitelText","height":47,"fontSize":35,"color":"#ffffff","align":"center","runtime":"laya.display.Text"},"compId":15}]}]},{"type":"Script","props":{"y":1,"x":0,"runtime":"Horizontal_wcjtn_LoopAd_wcjtn_View"},"compId":12}]},{"type":"Clip","props":{"visible":false,"skin":"comp/clip_num.png","right":0,"name":"BannerAD","left":0,"height":250,"bottom":0},"compId":4,"child":[{"type":"Script","props":{"runtime":"Banner_wcjtn_Ad_wcjtn_View"},"compId":9}]},{"type":"Script","props":{"runtime":"Universal_wcjtn_BottomZone"},"compId":16}]}],"loadList":["comp/clip_num.png"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}