/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameMgr from "./Mgr/GameMgr"
import BagView from "./MyScripts/View/BagView"
import SkinTitle from "./MyScripts/Ctrl/SkinTitle"
import MyList from "./Common/MyList"
import PageIcon from "./MyScripts/Ctrl/PageIcon"
import Coin from "./MyScripts/Ctrl/Coin"
import LoopAdBox from "./ShareAd/View/LoopAdBox"
import EnterPopVerticalLoopAdView from "./ShareAd/MyView/EnterPopVerticalLoopAdView"
import EnterGamePop from "./MyScripts/View/EnterGamePop"
import GameView from "./MyScripts/View/GameView"
import GameHeadPic from "./MyScripts/Ctrl/GameHeadPic"
import RecordVedioIcon from "./MyScripts/Ctrl/RecordVedioIcon"
import GuangQuan from "./MyScripts/Ctrl/GuangQuan"
import TreasureBox from "./MyScripts/Ctrl/TreasureBox"
import LotteryView from "./MyScripts/View/LotteryView"
import ButtonShan from "./MyScripts/Ctrl/ButtonShan"
import MyButton from "./Common/MyButton"
import SpriteBreath from "./Common/SpriteBreath"
import MenuView from "./MyScripts/View/MenuView"
import MenuSingleAniADView from "./ShareAd/MyView/MenuSingleAniADView"
import HorizontalLoopAdView from "./ShareAd/View/HorizontalLoopAdView"
import VerticalLoopAdView from "./ShareAd/MyView/VerticalLoopAdView"
import MoreGameView2 from "./MyScripts/View/MoreGameView2"
import MoreGameLoopAdBox from "./ShareAd/MyView/MoreGameLoopAdBox"
import MoreGameLoopAdView from "./ShareAd/MyView/MoreGameLoopAdView"
import MoreGameView from "./MyScripts/View/MoreGameView"
import NativeAdView from "./MyScripts/View/NativeAdView"
import OverDeriveView from "./MyScripts/View/OverDeriveView"
import OverView from "./MyScripts/View/OverView"
import OverCup from "./MyScripts/Ctrl/OverCup"
import Cup from "./MyScripts/Ctrl/Cup"
import HeadPic from "./MyScripts/Ctrl/HeadPic"
import RankView from "./MyScripts/View/RankView"
import ReliveView from "./MyScripts/View/ReliveView"
import WudianSprite from "./Common/WudianSprite"
import VerticalSideADLoopView from "./ShareAd/MyView/VerticalSideADLoopView"
import SideADView from "./MyScripts/View/SideADView"
import TrySkinView from "./MyScripts/View/TrySkinView"
import TwinkleSprite from "./View/TwinkleSprite"
import ClickGetPrize from "./View/ClickGetPrize/ClickGetPrize"
import LoadingView from "./View/LoadingView/LoadingView"
import TipsView from "./View/TipsView/TipsView"
import BannerAdView from "./ShareAd/View/BannerAdView"
import UniversalBottomZone from "./View/Common/UniversalBottomZone"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=750;
    static height:number=1334;
    static scaleMode:string="fixedwidth";
    static screenMode:string="vertical";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="GameMain.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("Mgr/GameMgr.ts",GameMgr);
        reg("MyScripts/View/BagView.ts",BagView);
        reg("MyScripts/Ctrl/SkinTitle.ts",SkinTitle);
        reg("Common/MyList.ts",MyList);
        reg("MyScripts/Ctrl/PageIcon.ts",PageIcon);
        reg("MyScripts/Ctrl/Coin.ts",Coin);
        reg("ShareAd/View/LoopAdBox.ts",LoopAdBox);
        reg("ShareAd/MyView/EnterPopVerticalLoopAdView.ts",EnterPopVerticalLoopAdView);
        reg("MyScripts/View/EnterGamePop.ts",EnterGamePop);
        reg("MyScripts/View/GameView.ts",GameView);
        reg("MyScripts/Ctrl/GameHeadPic.ts",GameHeadPic);
        reg("MyScripts/Ctrl/RecordVedioIcon.ts",RecordVedioIcon);
        reg("MyScripts/Ctrl/GuangQuan.ts",GuangQuan);
        reg("MyScripts/Ctrl/TreasureBox.ts",TreasureBox);
        reg("MyScripts/View/LotteryView.ts",LotteryView);
        reg("MyScripts/Ctrl/ButtonShan.ts",ButtonShan);
        reg("Common/MyButton.ts",MyButton);
        reg("Common/SpriteBreath.ts",SpriteBreath);
        reg("MyScripts/View/MenuView.ts",MenuView);
        reg("ShareAd/MyView/MenuSingleAniADView.ts",MenuSingleAniADView);
        reg("ShareAd/View/HorizontalLoopAdView.ts",HorizontalLoopAdView);
        reg("ShareAd/MyView/VerticalLoopAdView.ts",VerticalLoopAdView);
        reg("MyScripts/View/MoreGameView2.ts",MoreGameView2);
        reg("ShareAd/MyView/MoreGameLoopAdBox.ts",MoreGameLoopAdBox);
        reg("ShareAd/MyView/MoreGameLoopAdView.ts",MoreGameLoopAdView);
        reg("MyScripts/View/MoreGameView.ts",MoreGameView);
        reg("MyScripts/View/NativeAdView.ts",NativeAdView);
        reg("MyScripts/View/OverDeriveView.ts",OverDeriveView);
        reg("MyScripts/View/OverView.ts",OverView);
        reg("MyScripts/Ctrl/OverCup.ts",OverCup);
        reg("MyScripts/Ctrl/Cup.ts",Cup);
        reg("MyScripts/Ctrl/HeadPic.ts",HeadPic);
        reg("MyScripts/View/RankView.ts",RankView);
        reg("MyScripts/View/ReliveView.ts",ReliveView);
        reg("Common/WudianSprite.ts",WudianSprite);
        reg("ShareAd/MyView/VerticalSideADLoopView.ts",VerticalSideADLoopView);
        reg("MyScripts/View/SideADView.ts",SideADView);
        reg("MyScripts/View/TrySkinView.ts",TrySkinView);
        reg("View/TwinkleSprite.ts",TwinkleSprite);
        reg("View/ClickGetPrize/ClickGetPrize.ts",ClickGetPrize);
        reg("View/LoadingView/LoadingView.ts",LoadingView);
        reg("View/TipsView/TipsView.ts",TipsView);
        reg("ShareAd/View/BannerAdView.ts",BannerAdView);
        reg("View/Common/UniversalBottomZone.ts",UniversalBottomZone);
    }
}
GameConfig.init();