/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.View {
    export class LoadingUI extends Scene {
        public static  uiView:any ={"type":"Scene","props":{"width":750,"top":0,"right":0,"left":0,"height":1334,"bottom":0},"compId":2,"child":[{"type":"Box","props":{"y":0,"x":0,"width":750,"height":1700,"bgColor":"#afe790"},"compId":15},{"type":"Clip","props":{"top":360,"skin":"Loading/loadingcold.png","right":0,"name":"Bg"},"compId":6,"child":[{"type":"Sprite","props":{"y":720,"x":-86,"texture":"Loading/loadye.png"},"compId":9,"child":[{"type":"Clip","props":{"y":31,"x":16,"width":609,"skin":"Loading/loadedg.png","pivotY":22,"name":"processBar","height":37},"compId":5,"child":[{"type":"Sprite","props":{"y":2,"x":225,"texture":"Loading/Loadinglan.png"},"compId":11},{"type":"FontClip","props":{"x":356,"value":"0","spaceX":-5,"skin":"Loading/numloadnum.png","sheet":"0123456789","centerY":2},"compId":12,"child":[{"type":"Clip","props":{"skin":"Loading/xx.png","right":-23},"compId":14}]}]}]}]},{"type":"Script","props":{"y":0,"x":0,"runtime":"View/LoadingView/LoadingView.ts"},"compId":7},{"type":"Sprite","props":{"y":130,"x":104,"texture":"Loading/logo.png"},"compId":16},{"type":"Box","props":{"y":1700,"width":750,"name":"blackbox","height":1700,"bgColor":"#000000"},"compId":17}],"loadList":["Loading/loadingcold.png","Loading/loadye.png","Loading/loadedg.png","Loading/Loadinglan.png","Loading/numloadnum.png","Loading/xx.png","Loading/logo.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(LoadingUI.uiView);
        }
    }
    REG("ui.View.LoadingUI",LoadingUI);
}