/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameMgr from "./Mgr/GameMgr"
import KRQ_LoopAdBox from "./KRQ/Com/KRQ_LoopAd/KRQ_LoopAdBox"
import KRQ_VLoopAd from "./KRQ/Com/KRQ_LoopAd/KRQ_VLoopAd"
import KRQ_Banner from "./KRQ/Com/KRQ_Banner"
import KRQ_Export from "./KRQ/ViewCom/KRQ_Export"
import KRQ_RockSingleAd from "./KRQ/Com/KRQ_RockSingleAd"
import KRQ_Floating from "./KRQ/ViewCom/KRQ_Floating"
import KRQ_RollSingleAd from "./KRQ/Com/KRQ_RollSingleAd"
import KRQ_GameOver from "./KRQ/ViewCom/KRQ_GameOver"
import KRQ_SidePull from "./KRQ/ViewCom/KRQ_SidePull"
import KRQ_HLoopAd from "./KRQ/Com/KRQ_LoopAd/KRQ_HLoopAd"
import KRQ_Main from "./KRQ/ViewCom/KRQ_Main"
import KRQ_HistoryBox from "./KRQ/Com/KRQ_History/KRQ_HistoryBox"
import KRQ_History from "./KRQ/Com/KRQ_History/KRQ_History"
import KRQ_SingleAd from "./KRQ/Com/KRQ_SingleAd"
import TwinkleSprite from "./View/TwinkleSprite"
import ClickGetPrize from "./View/ClickGetPrize/ClickGetPrize"
import ButtonAnim from "./View/ButtonAnim"
import SkeletonPlayWin from "./Scrips/MyView/GameView/MainView/SkeletonPlayWin"
import GameOverView from "./Scrips/MyView/GameView/GameOverView/GameOverView"
import Controller from "./Script/GameView/Controller"
import GameView from "./Scrips/MyView/GameView/GameView/GameView"
import Gold from "./Scrips/MyView/GameView/MainView/Gold"
import BadTooth from "./Scrips/MyView/GameView/GameView/BadTooth"
import ToothShow from "./Scrips/MyView/GameView/GameView/ToothShow"
import ShowLever from "./Scrips/MyView/GameView/MainView/ShowLever"
import LoadingView from "./View/LoadingView/LoadingView"
import SkeletonPlay from "./Scrips/MyView/GameView/MainView/SkeletonPlay"
import JumpButton from "./Scrips/MyView/GameView/MainView/JumpButton"
import MainView from "./Scrips/MyView/GameView/MainView/MainView"
import MoreGameView from "./Scrips/MyView/GameView/MoreGameView/MoreGameView"
import TipsView from "./View/TipsView/TipsView"
import LoopAdBox from "./ShareAd/View/LoopAdBox"
import HorizontalLoopAdView from "./ShareAd/View/HorizontalLoopAdView"
import BannerAdView from "./ShareAd/View/BannerAdView"
import UniversalBottomZone from "./View/Common/UniversalBottomZone"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=750;
    static height:number=1334;
    static scaleMode:string="fixedwidth";
    static screenMode:string="vertical";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="GameMain.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("Mgr/GameMgr.ts",GameMgr);
        reg("KRQ/Com/KRQ_LoopAd/KRQ_LoopAdBox.ts",KRQ_LoopAdBox);
        reg("KRQ/Com/KRQ_LoopAd/KRQ_VLoopAd.ts",KRQ_VLoopAd);
        reg("KRQ/Com/KRQ_Banner.ts",KRQ_Banner);
        reg("KRQ/ViewCom/KRQ_Export.ts",KRQ_Export);
        reg("KRQ/Com/KRQ_RockSingleAd.ts",KRQ_RockSingleAd);
        reg("KRQ/ViewCom/KRQ_Floating.ts",KRQ_Floating);
        reg("KRQ/Com/KRQ_RollSingleAd.ts",KRQ_RollSingleAd);
        reg("KRQ/ViewCom/KRQ_GameOver.ts",KRQ_GameOver);
        reg("KRQ/ViewCom/KRQ_SidePull.ts",KRQ_SidePull);
        reg("KRQ/Com/KRQ_LoopAd/KRQ_HLoopAd.ts",KRQ_HLoopAd);
        reg("KRQ/ViewCom/KRQ_Main.ts",KRQ_Main);
        reg("KRQ/Com/KRQ_History/KRQ_HistoryBox.ts",KRQ_HistoryBox);
        reg("KRQ/Com/KRQ_History/KRQ_History.ts",KRQ_History);
        reg("KRQ/Com/KRQ_SingleAd.ts",KRQ_SingleAd);
        reg("View/TwinkleSprite.ts",TwinkleSprite);
        reg("View/ClickGetPrize/ClickGetPrize.ts",ClickGetPrize);
        reg("View/ButtonAnim.ts",ButtonAnim);
        reg("Scrips/MyView/GameView/MainView/SkeletonPlayWin.ts",SkeletonPlayWin);
        reg("Scrips/MyView/GameView/GameOverView/GameOverView.ts",GameOverView);
        reg("Script/GameView/Controller.ts",Controller);
        reg("Scrips/MyView/GameView/GameView/GameView.ts",GameView);
        reg("Scrips/MyView/GameView/MainView/Gold.ts",Gold);
        reg("Scrips/MyView/GameView/GameView/BadTooth.ts",BadTooth);
        reg("Scrips/MyView/GameView/GameView/ToothShow.ts",ToothShow);
        reg("Scrips/MyView/GameView/MainView/ShowLever.ts",ShowLever);
        reg("View/LoadingView/LoadingView.ts",LoadingView);
        reg("Scrips/MyView/GameView/MainView/SkeletonPlay.ts",SkeletonPlay);
        reg("Scrips/MyView/GameView/MainView/JumpButton.ts",JumpButton);
        reg("Scrips/MyView/GameView/MainView/MainView.ts",MainView);
        reg("Scrips/MyView/GameView/MoreGameView/MoreGameView.ts",MoreGameView);
        reg("View/TipsView/TipsView.ts",TipsView);
        reg("ShareAd/View/LoopAdBox.ts",LoopAdBox);
        reg("ShareAd/View/HorizontalLoopAdView.ts",HorizontalLoopAdView);
        reg("ShareAd/View/BannerAdView.ts",BannerAdView);
        reg("View/Common/UniversalBottomZone.ts",UniversalBottomZone);
    }
}
GameConfig.init();