/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.View {
    export class LoadingUI extends Scene {
        public static  uiView:any ={"type":"Scene","props":{"width":750,"top":0,"right":0,"left":0,"height":1334,"bottom":0},"compId":2,"child":[{"type":"Clip","props":{"y":0,"x":1,"width":750,"skin":"Loading/Juxing.png","name":"Bg","height":1334},"compId":6,"child":[{"type":"Clip","props":{"right":0,"name":"BottomZone","left":0,"height":570,"bottom":99},"compId":23,"child":[{"type":"Clip","props":{"y":327,"x":376,"width":615,"skin":"Loading/loadingxiatiao.png","pivotY":22,"pivotX":308,"name":"processBarBg","height":44,"sizeGrid":"0,25,0,25"},"compId":8,"child":[{"type":"Clip","props":{"width":594,"skin":"Loading/loadingshangtiao.png","pivotY":13,"name":"processBar","left":11,"height":26,"bottom":8,"sizeGrid":"0,12,0,12"},"compId":5},{"type":"Sprite","props":{"y":-23,"x":308,"width":143,"texture":"Loading/ziyuanjiazaizhong.png","pivotY":12,"pivotX":72,"height":23},"compId":10}]}]},{"type":"Clip","props":{"top":200,"skin":"Loading/Logo.png","name":"Logo","centerX":0},"compId":24}]},{"type":"Script","props":{"y":0,"x":0,"runtime":"View/LoadingView/LoadingView.ts"},"compId":7}],"loadList":["Loading/Juxing.png","Loading/loadingxiatiao.png","Loading/loadingshangtiao.png","Loading/ziyuanjiazaizhong.png","Loading/Logo.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(LoadingUI.uiView);
        }
    }
    REG("ui.View.LoadingUI",LoadingUI);
}