/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.View {
    export class LoadingUI extends Scene {
        public static  uiView:any ={"type":"Scene","props":{"width":750,"top":0,"right":0,"left":0,"height":1334,"bottom":0},"compId":2,"child":[{"type":"Clip","props":{"y":0,"x":1,"width":750,"name":"Bg","height":1334},"compId":6,"child":[{"type":"Clip","props":{"right":0,"name":"BottomZone","left":0,"height":570,"bottom":100},"compId":23,"child":[{"type":"Clip","props":{"y":326,"x":376,"width":615,"skin":"Loading/loadingxiatiao.png","pivotY":22,"pivotX":308,"name":"processBarBg","height":44,"sizeGrid":"0,25,0,25"},"compId":8,"child":[{"type":"Clip","props":{"y":22,"x":10,"width":594,"skin":"Loading/loadingshangtiao.png","pivotY":13,"name":"processBar","left":11,"height":26,"bottom":9,"sizeGrid":"0,12,0,12"},"compId":5},{"type":"Sprite","props":{"y":-24,"x":292,"width":143,"texture":"Loading/ziyuanjiazaizhong.png","pivotY":12,"pivotX":72,"height":23},"compId":10,"child":[{"type":"Sprite","props":{"y":15,"x":149,"width":6,"texture":"Loading/jiazaidunhao.png","height":5},"compId":11},{"type":"Sprite","props":{"y":15,"x":159,"width":6,"texture":"Loading/jiazaidunhao.png","height":5},"compId":12},{"type":"Sprite","props":{"y":15,"x":168,"width":6,"texture":"Loading/jiazaidunhao.png","height":5},"compId":13}]}]}]}]},{"type":"Script","props":{"y":0,"x":0,"runtime":"View/LoadingView/LoadingView.ts"},"compId":7},{"type":"Image","props":{"x":117,"width":516,"top":100,"skin":"Loading/我的车技特牛logo2.min.png","name":"logo","height":357},"compId":25}],"loadList":["Loading/loadingxiatiao.png","Loading/loadingshangtiao.png","Loading/ziyuanjiazaizhong.png","Loading/jiazaidunhao.png","Loading/我的车技特牛logo2.min.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(LoadingUI.uiView);
        }
    }
    REG("ui.View.LoadingUI",LoadingUI);
}