/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameMgr from "./Mgr/GameMgr"
import LoadingView from "./View/LoadingView/LoadingView"
import ButtonAnim from "./View/ButtonAnim"
import SkinTips from "./View/SkinTips/SkinTips"
import KRQ_LoopAdBox from "./KRQ/Com/KRQ_LoopAd/KRQ_LoopAdBox"
import KRQ_VLoopAd from "./KRQ/Com/KRQ_LoopAd/KRQ_VLoopAd"
import Exprot2ViewTemplate from "./View/TemplateViews/Export2/Exprot2ViewTemplate"
import ViewAutoScaleByW from "./View/Common/ViewAutoScaleByW"
import Exprot3ViewTemplate from "./View/TemplateViews/Export3/Exprot3ViewTemplate"
import GameFailViewTemplate from "./View/TemplateViews/GameFail/GameFailViewTemplate"
import GameWinViewTemplate from "./View/TemplateViews/GameWin/GameWinViewTemplate"
import GameInfo from "./View/TemplateViews/InGame/GameInfo"
import Input from "./View/TemplateViews/InGame/Input"
import InGameViewTemplate from "./View/TemplateViews/InGame/InGameViewTemplate"
import Ani from "./View/TemplateViews/Main/Ani"
import MainViewTemplate from "./View/TemplateViews/Main/MainViewTemplate"
import MiniGameViewTemplate from "./View/TemplateViews/MiniGame/MiniGameViewTemplate"
import KRQ_HistoryBox from "./KRQ/Com/KRQ_History/KRQ_HistoryBox"
import KRQ_History from "./KRQ/Com/KRQ_History/KRQ_History"
import WXCrazyClick from "./View/TemplateViews/WXCrazyClick/WXCrazyClick"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=750;
    static height:number=1334;
    static scaleMode:string="fixedwidth";
    static screenMode:string="vertical";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="GameMain.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("Mgr/GameMgr.ts",GameMgr);
        reg("View/LoadingView/LoadingView.ts",LoadingView);
        reg("View/ButtonAnim.ts",ButtonAnim);
        reg("View/SkinTips/SkinTips.ts",SkinTips);
        reg("KRQ/Com/KRQ_LoopAd/KRQ_LoopAdBox.ts",KRQ_LoopAdBox);
        reg("KRQ/Com/KRQ_LoopAd/KRQ_VLoopAd.ts",KRQ_VLoopAd);
        reg("View/TemplateViews/Export2/Exprot2ViewTemplate.ts",Exprot2ViewTemplate);
        reg("View/Common/ViewAutoScaleByW.ts",ViewAutoScaleByW);
        reg("View/TemplateViews/Export3/Exprot3ViewTemplate.ts",Exprot3ViewTemplate);
        reg("View/TemplateViews/GameFail/GameFailViewTemplate.ts",GameFailViewTemplate);
        reg("View/TemplateViews/GameWin/GameWinViewTemplate.ts",GameWinViewTemplate);
        reg("View/TemplateViews/InGame/GameInfo.ts",GameInfo);
        reg("View/TemplateViews/InGame/Input.ts",Input);
        reg("View/TemplateViews/InGame/InGameViewTemplate.ts",InGameViewTemplate);
        reg("View/TemplateViews/Main/Ani.ts",Ani);
        reg("View/TemplateViews/Main/MainViewTemplate.ts",MainViewTemplate);
        reg("View/TemplateViews/MiniGame/MiniGameViewTemplate.ts",MiniGameViewTemplate);
        reg("KRQ/Com/KRQ_History/KRQ_HistoryBox.ts",KRQ_HistoryBox);
        reg("KRQ/Com/KRQ_History/KRQ_History.ts",KRQ_History);
        reg("View/TemplateViews/WXCrazyClick/WXCrazyClick.ts",WXCrazyClick);
    }
}
GameConfig.init();