/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package {
	import laya.utils.ClassUtils;
	import Game_wcjtn_Mgr;
	import laya.display.Text;
	import KRQ_wcjtn__Loop_wcjtn_Ad_wcjtn_Box;
	import KRQ_wcjtn__V_wcjtn_Loop_wcjtn_Ad;
	import KRQ_wcjtn__Banner_wcjtn_;
	import KRQ_wcjtn__Export_wcjtn_;
	import KRQ__wcjtn_History_wcjtn_Box;
	import KRQ_wcjtn__His_wcjtn_tory;
	import KRQ_wcjtn__Rock_wcjtn_Single_wcjtn_Ad;
	import KRQ_wcjtn__Floating_wcjtn_;
	import KRQ_Roll_wcjtn_Single_wcjtn_Ad;
	import KRQ_wcjtn__Game_wcjtn_Over;
	import KRQ_wcjtn__Side_wcjtn_Pull;
	import KRQ_wcjtn__H_wcjtn_Loop_wcjtn_Ad;
	import KRQ_wcjtn__Main_wcjtn_;
	import KRQ_wcjtn__Single_wcjtn_Ad;
	import KRQ_Gaming_wcjtn_Banner;
	import Twinkle_wcjtn_Sprite;
	import Click_wcjtn_Get_wcjtn_Prize;
	import Logo_wcjtn_Ani;
	import Loading_wcjtn_View;
	import Circular_wcjtn_ProcessBar;
	import ReliveBtn;
	import GameView;
	import Button_wcjtn_Anim;
	import MyMainView;
	import Exprot2_wcjtn_View_wcjtn_Template;
	import ExportViewTemplate;
	import Game_wcjtn_Fail_wcjtn_View_wcjtn_Template;
	import Game_wcjtn_Win_wcjtn_ViewTemplate;
	import In_wcjtn_Game_wcjtn_View_wcjtn_Template;
	import Main_wcjtn_View_wcjtn_Template;
	import Mini_wcjtn_Game_wcjtn_View_wcjtn_Template;
	import OPPO_wcjtn_NativeAd_wcjtn_ViewTemplate;
	import Reward_wcjtn_View_wcjtn_Template;
	import Tips_wcjtn_View;
	import LoopAd_wcjtn_Box;
	import Horizontal_wcjtn_LoopAd_wcjtn_View;
	import Banner_wcjtn_Ad_wcjtn_View;
	import Universal_wcjtn_BottomZone;
	/**
	 * 游戏初始化配置
	 */
	public class GameConfig {
		public static var width:int = 1136;
		public static var height:int = 640;
		public static var scaleMode:String = "showall";
		public static var screenMode:String = "none";
		public static var alignV:String = "top";
		public static var alignH:String = "left";
		public static var startScene:* = "View/MyViews/MainView.scene";
		public static var sceneRoot:String = "";
		public static var debug:Boolean = false;
		public static var stat:Boolean = false;
		public static var physicsDebug:Boolean = false;
		public static var exportSceneToJson:Boolean = false;
		
		public static function init():void {
			//注册Script或者Runtime引用
			var reg:Function = ClassUtils.regClass;
			reg("Game_wcjtn_Mgr",Game_wcjtn_Mgr);
			reg("laya.display.Text",Text);
			reg("KRQ_wcjtn__Loop_wcjtn_Ad_wcjtn_Box",KRQ_wcjtn__Loop_wcjtn_Ad_wcjtn_Box);
			reg("KRQ_wcjtn__V_wcjtn_Loop_wcjtn_Ad",KRQ_wcjtn__V_wcjtn_Loop_wcjtn_Ad);
			reg("KRQ_wcjtn__Banner_wcjtn_",KRQ_wcjtn__Banner_wcjtn_);
			reg("KRQ_wcjtn__Export_wcjtn_",KRQ_wcjtn__Export_wcjtn_);
			reg("KRQ__wcjtn_History_wcjtn_Box",KRQ__wcjtn_History_wcjtn_Box);
			reg("KRQ_wcjtn__His_wcjtn_tory",KRQ_wcjtn__His_wcjtn_tory);
			reg("KRQ_wcjtn__Rock_wcjtn_Single_wcjtn_Ad",KRQ_wcjtn__Rock_wcjtn_Single_wcjtn_Ad);
			reg("KRQ_wcjtn__Floating_wcjtn_",KRQ_wcjtn__Floating_wcjtn_);
			reg("KRQ_Roll_wcjtn_Single_wcjtn_Ad",KRQ_Roll_wcjtn_Single_wcjtn_Ad);
			reg("KRQ_wcjtn__Game_wcjtn_Over",KRQ_wcjtn__Game_wcjtn_Over);
			reg("KRQ_wcjtn__Side_wcjtn_Pull",KRQ_wcjtn__Side_wcjtn_Pull);
			reg("KRQ_wcjtn__H_wcjtn_Loop_wcjtn_Ad",KRQ_wcjtn__H_wcjtn_Loop_wcjtn_Ad);
			reg("KRQ_wcjtn__Main_wcjtn_",KRQ_wcjtn__Main_wcjtn_);
			reg("KRQ_wcjtn__Single_wcjtn_Ad",KRQ_wcjtn__Single_wcjtn_Ad);
			reg("KRQ_Gaming_wcjtn_Banner",KRQ_Gaming_wcjtn_Banner);
			reg("Twinkle_wcjtn_Sprite",Twinkle_wcjtn_Sprite);
			reg("Click_wcjtn_Get_wcjtn_Prize",Click_wcjtn_Get_wcjtn_Prize);
			reg("Logo_wcjtn_Ani",Logo_wcjtn_Ani);
			reg("Loading_wcjtn_View",Loading_wcjtn_View);
			reg("Circular_wcjtn_ProcessBar",Circular_wcjtn_ProcessBar);
			reg("ReliveBtn",ReliveBtn);
			reg("GameView",GameView);
			reg("Button_wcjtn_Anim",Button_wcjtn_Anim);
			reg("MyMainView",MyMainView);
			reg("Exprot2_wcjtn_View_wcjtn_Template",Exprot2_wcjtn_View_wcjtn_Template);
			reg("ExportViewTemplate",ExportViewTemplate);
			reg("Game_wcjtn_Fail_wcjtn_View_wcjtn_Template",Game_wcjtn_Fail_wcjtn_View_wcjtn_Template);
			reg("Game_wcjtn_Win_wcjtn_ViewTemplate",Game_wcjtn_Win_wcjtn_ViewTemplate);
			reg("In_wcjtn_Game_wcjtn_View_wcjtn_Template",In_wcjtn_Game_wcjtn_View_wcjtn_Template);
			reg("Main_wcjtn_View_wcjtn_Template",Main_wcjtn_View_wcjtn_Template);
			reg("Mini_wcjtn_Game_wcjtn_View_wcjtn_Template",Mini_wcjtn_Game_wcjtn_View_wcjtn_Template);
			reg("OPPO_wcjtn_NativeAd_wcjtn_ViewTemplate",OPPO_wcjtn_NativeAd_wcjtn_ViewTemplate);
			reg("Reward_wcjtn_View_wcjtn_Template",Reward_wcjtn_View_wcjtn_Template);
			reg("Tips_wcjtn_View",Tips_wcjtn_View);
			reg("LoopAd_wcjtn_Box",LoopAd_wcjtn_Box);
			reg("Horizontal_wcjtn_LoopAd_wcjtn_View",Horizontal_wcjtn_LoopAd_wcjtn_View);
			reg("Banner_wcjtn_Ad_wcjtn_View",Banner_wcjtn_Ad_wcjtn_View);
			reg("Universal_wcjtn_BottomZone",Universal_wcjtn_BottomZone);
		}
		GameConfig.init();
	}
}